### ISSUE TITLE
Deprecating announce?

### ISSUE THREAD

**Issue by dbalan** [hillhacks/website#1]
hillhackers-announce is missing from mailing lists, are we deprecating announce?

**Comment by ppaeps** [comment]
There are only 44 subscribers to announce@, only 24 of whom are not on hillhackers@.  For comparison: there are nearly 400 subscribers to hillhackers@.

I don't mind keeping it but if we do, we should remember to use it.

**Comment by dbalan** [comment]
Makes sense. 

Maybe we can wait a bit and push no longer updated message there..
